spring:
  datasource:
    url: jdbc:h2:mem:cursosdb
    username: h2
    password:
    driverClassName: org.h2.Driver
  sql.init.mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2


